# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-08-23 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170823_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizz',
            old_name='url',
            new_name='link',
        ),
        migrations.AddField(
            model_name='quizz',
            name='category',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
    ]
